apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rbac.yaml
- secrets/dockerhub-creds.yaml
- secrets/github-instavote-deploy.yaml
- secrets/github-token.yaml
- secrets/slack-url.yaml
- secrets/webhook-token.yaml
- instavote-deploy-gitrepository.yaml
- instavote-deploy-kustomization.yaml
